import type { SalaryBreakdown, SalaryInput } from "@/lib/types/salary.types";
import { deferExecution } from "@/lib/scheduling/defer-execution";
import { formatCurrency } from "./format-currency";

/**
 * Build CSV rows from salary breakdown.
 * Structure:
 *  - Header block (name, CTC, regime, date)
 *  - Summary section
 *  - Component-by-component rows
 */
export function buildSalaryCSV(
  breakdown: SalaryBreakdown,
  input: SalaryInput
): string {
  const rows: string[][] = [];

  const esc = (v: string | number) => {
    const s = String(v);
    // Quote cells that contain commas, quotes, or newlines
    if (/[",\n\r]/.test(s)) return `"${s.replace(/"/g, '""')}"`;
    return s;
  };
  const row = (...cells: (string | number)[]) => rows.push(cells.map(esc));

  const date = new Date().toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });

  // ── Header ──
  row("InHand Salary Report");
  row("Generated", date);
  if (input.fullName?.trim()) row("Name", input.fullName.trim());
  row("Tax Regime", input.taxRegime === "old" ? "Old Regime" : "New Regime");
  row("City Tier", input.cityTier === "tier1" ? "Tier 1 – Metro" : input.cityTier === "tier2" ? "Tier 2 – Urban" : "Tier 3 – Semi-Urban");
  row("");

  // ── Summary ──
  row("SUMMARY", "", "");
  row("", "Monthly", "Annual");
  row("CTC (Stated)", formatCurrency(Math.round(breakdown.statedAnnualCTC / 12)), formatCurrency(breakdown.statedAnnualCTC));
  row("In-hand (excl. variable)", formatCurrency(breakdown.monthlyInHandExcludingVariable), formatCurrency(breakdown.monthlyInHandExcludingVariable * 12));
  if (breakdown.annualVariableCashTotal > 0) {
    row("In-hand (incl. variable)", formatCurrency(breakdown.monthlyInHandIncludingVariable), formatCurrency(breakdown.annualCashCompensation));
  }
  row("Income Tax (TDS)", formatCurrency(Math.round(breakdown.annualIncomeTax / 12)), formatCurrency(breakdown.annualIncomeTax));
  row("Total Deductions", formatCurrency(breakdown.totalMonthlyDeductions), formatCurrency(breakdown.totalMonthlyDeductions * 12));
  row("Take-home %", `${breakdown.takeHomePercent}%`, "");
  row("");

  // ── Component table ──
  row("SALARY COMPONENTS", "", "", "", "");
  row("Component", "Description", "Monthly Value", "Annual Value", "Type", "Group");

  for (const c of breakdown.components) {
    if (c.monthlyValue === 0 && c.annualValue === 0) continue;
    const typeLabel =
      c.type === "earning"
        ? "Earning"
        : c.type === "deduction"
          ? "Deduction"
          : c.type === "tax-free"
            ? "Tax Free"
            : "Employer";
    const groupLabel =
      c.group === "earnings"
        ? "Earnings"
        : c.group === "deductions"
          ? "Deductions"
          : "Employer CTC";
    row(c.name, c.description, formatCurrency(c.monthlyValue), formatCurrency(c.annualValue), typeLabel, groupLabel);
  }

  row("");
  row("Note: Figures are estimates based on standard CTC structure. Verify with your employer.");
  row("Generated by InHand · inhand.app");

  return rows.map((r) => r.join(",")).join("\n");
}

/** Trigger a client-side CSV download in the browser. */
export function downloadCSV(csv: string, filename: string): void {
  const blob = new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8;" }); // BOM for Excel
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.style.display = "none";
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  deferExecution(5000, () => URL.revokeObjectURL(url));
}

/** Shared basename for exports, e.g. `inhand-salary-25lpa-2026-04` */
export function salaryExportBasename(annualCTC: number): string {
  const lpa = (annualCTC / 100_000).toFixed(1).replace(".0", "");
  const month = new Date().toISOString().slice(0, 7);
  return `inhand-salary-${lpa}lpa-${month}`;
}

/** Safe CSV filename */
export function salaryCSVFilename(annualCTC: number): string {
  return `${salaryExportBasename(annualCTC)}.csv`;
}

/** Safe PDF filename */
export function salaryPDFFilename(annualCTC: number): string {
  return `${salaryExportBasename(annualCTC)}.pdf`;
}
